server:
  port: 8091

spring:
  application:
    name: naco-provider-service
  cloud:
    nacos:
      discovery:
        server-addr: http://43.154.63.136:8848
        username: nacos
        password: nacos