server:
  port: 8090

spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: http://43.154.63.136:8848
        username: nacos
        password: nacos
