server:
  port: 8092

spring:
  application:
    name: goods-service
  cloud:
    nacos:
      discovery:
        server-addr: http://43.154.63.136:8848
        username: nacos
        password: nacos
